project:
  type: website
  output-dir: docs

website:
  title: "生物实验方法"
  search: true
  back-to-top-navigation: true
  reader-mode: true
    
  navbar:
    background: info
    left:
      - text: "主页"
        href: index.md
      - text: "实验流程"
        href: protocol.md
    
        
  sidebar:
    - title:  "实验流程"
      style: "docked"
      background: "#ffd9e6"
      foreground: "#87cefa"
      border: true
      alignment: left
      collapse-level: 4
      contents: 
        - protocol.md
        - section: "cell"
          contents: 
            - PBMCsIsolationFreezing.md
            
        - section: "protein"
          contents: 
            - WB+Co-IP.md
            - ELISA.md
            
        - section: "nucleic acid"
          contents: 
            - PCR.md
            - real-time_ReverseTranscription-PCR.md
            - plasmidDNA_purification_digestion_identification.md
            - TransformationCaCl2.md
       
       
    # - title: "Table"
    #   contents: 
    #     - Table.qmd
       

format:
  html:
    theme: cosmo
editor: visual

