project:
  type: book
  output-dir: docs

book:
  title: "实验方法"
  chapters:
    - index.md
    - part: "cell"
      chapters: 
        - PBMCsIsolationFreezing.md
        
        
    - part: "protein"
      chapters:
        - WB+Co-IP.md
        - ELISA.md
    
    
    - part: "DNA"
      chapters:
        - PCR.md
        - real-time_ReverseTranscription-PCR.md
        - plasmidDNA_purification_digestion_identification.md
        - TransformationCaCl2.md


 

format:
  html:
    theme: cosmo
editor: visual

